export TERM="xterm-256color"
export EDITOR="nvim"
export ZSH_PLUGINS_ALIAS_TIPS_TEXT="Alias tip: "
export ZSH_PLUGINS_ALIAS_TIPS_EXCLUDES="_"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source Secret.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/secret/env.sh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/secret/env.sh"
fi

SPACESHIP_CHAR_SYMBOL='ᗎ '
SPACESHIP_VENV_COLOR='208'
SPACESHIP_VENV_SYMBOL=' '

SPACESHIP_PROMPT_ORDER=(
  venv          # virtualenv section
  dir           # Current directory section
  git           # Git section (git_branch + git_status)
  package       # Package version
  node          # Node.js section
  aws           # Amazon Web Services section
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  line_sep      # Line break
  char          # Prompt character
)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# List directory contents
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

alias ls='exa -F'
alias l='exa -F'
alias ll='exa -lahF'
alias lll='exa -baghHliSF@'

alias v='nvim'
alias vi='nvim'
alias vim='nvim'

alias glg='git log --date-order --all --graph --format="%C(green)%h%Creset %C(yellow)%an%Creset %C(blue bold)%ar%Creset %C(red bold)%d%Creset%s"'
alias glg2='git log --date-order --all --graph --name-status --format="%C(green)%H%Creset %C(yellow)%an%Creset %C(blue bold)%ar%Creset %C(red bold)%d%Creset%s"'

alias cll='colorls -la --report --gs'
alias cat='bat'
alias mux='tmuxinator'
alias copy="tr -d '\n' | pbcopy"
alias run="open -a 'Google Chrome Canary' --args --disable-web-security --user-data-dir='/Users/gupta/Desktop/nosecurity'"

setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

# clear
# neofetch

. /Users/gupta/.zprezto/z.sh
